### ISSUE TITLE
Options for loadURL are not passed on (extraHeaders)

### ISSUE THREAD

**Issue by pbootsma** [gerhardberger/electron-pdf-window#10]
LoadUrl has options: BrowserWindow.loadURL(url [, options])
https://github.com/electron/electron/blob/master/docs/api/browser-window.md

I would like to pass { extraHeaders: 'Authorization: Bearer XXXXXXXX' } as options param.
This works with a normal BrowserWindow, but not with a PDFWindow.

**Comment by gerhardberger** [comment]
added in [`71f5d98`](https://github.com/gerhardberger/electron-pdf-window/commit/71f5d98491e824ec20edbd78f268d795008a4871)

**Comment by pbootsma** [comment]
Thanks!
