### ISSUE TITLE
Could not call remote function 'BrowserWindow'

### ISSUE THREAD

**Issue by leonliang33** [gerhardberger/electron-pdf-window#14]
Hey I'm trying to test run the PDFWindow from the electron console 
`win = new PDFWindow()
win.loadURL('http://www.aclweb.org/anthology/P/P02/P02-1022.pdf')`
but this the error message I'm getting:

remote.js:217 Uncaught Error: Could not call remote function 'BrowserWindow'. Check that the function signature is correct. Underlying error: Requires constructor call(…)
metaToValue @ remote.js:217
remoteFunction @ remote.js:234
PDFWindow @ index.js:57
(anonymous function) @ VM415:1

**Comment by leonliang33** [comment]
I think this is because BrowserWindow is no longer extendable see: https://github.com/electron/electron/issues/23

**Comment by gerhardberger** [comment]
yeah, you need to use the `addSupport` method not `PDFWindow` directly.

Duplicate of #2.
