### ISSUE TITLE
加载本地pdf一直是空白

### ISSUE THREAD

**Issue by LuoRiWuSheng** [gerhardberger/electron-pdf-window#35]
webview = document.getElementById("webview")  
let area = document.querySelector(".webview-area")   
 const PDFWindow = require('electron-pdf-window')
   const win = new BrowserWindow({
          width: 800, 
          height: 600 ,
          webPreferences: {
            plugins: true
           }
    })
    PDFWindow.addSupport(win)
    win.loadURL("file:1.pdf"))
`
上面的这样不行，也不报错，pdf也不显示

我的1.pdf在当前页面的同级目录

需要需改一下loadURL地址才行， 使用path模块
` PDFWindow.addSupport(win)
  const path = require("path")
   win.loadURL(path.resolve(__dirname, "1.pdf"))`

这样就没问题
将就着看吧   github这个markdown的解析真的是醉醉的

**Comment by isunbeam** [comment]
麻烦问下，在线预览pdf怎样实现啊？必须要把网络pdf地址下载到本地之后，然后再用这个插件的方式使用吗？我为什么一直都是显示空白呢？

**Comment by LuoRiWuSheng** [comment]
> 麻烦问下，在线预览pdf怎样实现啊？必须要把网络pdf地址下载到本地之后，然后再用这个插件的方式使用吗？我为什么一直都是显示空白呢？

**Comment by LuoRiWuSheng** [comment]
> 麻烦问下，在线预览pdf怎样实现啊？必须要把网络pdf地址下载到本地之后，然后再用这个插件的方式使用吗？我为什么一直都是显示空白呢？

不是的，这个可以直接加载服务器的pdf文件，这个主要是要了解 pdfjs这个插件的用法就行，并不在于 electron是怎么样子的

**Comment by isunbeam** [comment]
麻烦能不能给个例子呢，我这样写了之后没效果，打开的窗口一片空白，而且好像说是不允许访问
const { BrowserWindow } = require('electron').remote
const PDFWindow = require('electron-pdf-window')

const win = new BrowserWindow({ width: 800, height: 600 })

PDFWindow.addSupport(win)

win.loadURL('http://mozilla.github.io/pdf.js/web/compressed.tracemonkey-pldi-09.pdf')







我用的electron是4.0版本
能不能麻烦解答一下是什么原因


------------------ 原始邮件 ------------------
发件人: "LuoRiWuSheng"<notifications@github.com>;
发送时间: 2019年10月22日(星期二) 中午1:54
收件人: "gerhardberger/electron-pdf-window"<electron-pdf-window@noreply.github.com>;
抄送: "赵建军"<386285212@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [gerhardberger/electron-pdf-window] 加载本地pdf一直是空白 (#35)



 
麻烦问下，在线预览pdf怎样实现啊？必须要把网络pdf地址下载到本地之后，然后再用这个插件的方式使用吗？我为什么一直都是显示空白呢？
  
不是的，这个可以直接加载服务器的pdf文件，这个主要是要了解 pdfjs这个插件的用法就行，并不在于 electron是怎么样子的
