### ISSUE TITLE
iframe support possible

### ISSUE THREAD

**Issue by sbittmann** [gerhardberger/electron-pdf-window#8]
Is it possible to support iframes inside the PDFWindow

Using 
```
<html><body>
<iframe width="500" height="500" src="test.pdf"></iframe>
</body></html>
```

only brings up a "Save As Dialog"

**Comment by haribabu500** [comment]
same issue. guess not possible...

**Comment by natchkebiailia** [comment]
@sbittmann @haribabu500 
You have to change url in iframe src:

change
` src="filename.pdf"`
 to
 `src="path_to_pdfjs_viewer.html?file=filename.pdf"`

You can also use external library url:
`src="https://mozilla.github.io/pdf.js/web/viewer.html?file=filename.pdf"`
**N.B** you have to encodeURIComponent("filename.pdf") before passing as a parameter

**Comment by Erim32** [comment]
Hello, any update  ?

**Comment by ram-you** [comment]
Hi , you can use Webview in place of iframe : 

`  var webview = document.querySelector('webview');`

`//important : webview have not webContents like browser window do`

`   webview.webContents =  webview.getWebContents();`

`    PDFWindow.addSupport(webview);`

Then 
`webview.loadURL(yourFile.pdf)`

Hope this help.
